/*
 *  Copyright (C) 2011 phuseman
 * 
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.bielefeld.uni.cebitec.dotplotviewer;

import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;

//according to this tutorial:
//http://platform.netbeans.org/tutorials/nbm-options.html
final class DotPlotViewerPanel extends javax.swing.JPanel {

  public static final String PROP_GRID = "grid";
  public static final String PROP_REVERSE = "reverseContigs";
  public static final String PROP_STACK = "stackContigs";
  private final DotPlotViewerOptionsPanelController controller;
  private final Preferences prefs;

  DotPlotViewerPanel(DotPlotViewerOptionsPanelController controller) {
    this.controller = controller;
    this.prefs = NbPreferences.forModule(DotPlotViewerPanel.class);
    initComponents();
    // TODO listen to changes in form fields and call controller.changed()
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    grid = new javax.swing.JCheckBox();
    reverseContigs = new javax.swing.JCheckBox();
    stackContigs = new javax.swing.JCheckBox();

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    org.openide.awt.Mnemonics.setLocalizedText(grid, org.openide.util.NbBundle.getMessage(DotPlotViewerPanel.class, "DotPlotViewerPanel.grid.text")); // NOI18N
    grid.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gridActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(reverseContigs, org.openide.util.NbBundle.getMessage(DotPlotViewerPanel.class, "DotPlotViewerPanel.reverseContigs.text")); // NOI18N
    reverseContigs.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reverseContigsActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(stackContigs, org.openide.util.NbBundle.getMessage(DotPlotViewerPanel.class, "DotPlotViewerPanel.stackContigs.text")); // NOI18N
    stackContigs.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stackContigsActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(grid)
          .addComponent(stackContigs)
          .addComponent(reverseContigs))
        .addContainerGap(251, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(grid)
        .addGap(4, 4, 4)
        .addComponent(reverseContigs)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(stackContigs)
        .addContainerGap(126, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void gridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridActionPerformed
    prefs.putBoolean(DotPlotViewerPanel.PROP_GRID, grid.isSelected());
    controller.changed();
  }//GEN-LAST:event_gridActionPerformed

  private void reverseContigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseContigsActionPerformed
    prefs.putBoolean(DotPlotViewerPanel.PROP_REVERSE, reverseContigs.isSelected());
    controller.changed();
  }//GEN-LAST:event_reverseContigsActionPerformed

  private void stackContigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackContigsActionPerformed
    prefs.putBoolean(DotPlotViewerPanel.PROP_STACK, stackContigs.isSelected());
    controller.changed();
  }//GEN-LAST:event_stackContigsActionPerformed

  void load() {
    grid.setSelected(prefs.getBoolean(DotPlotViewerPanel.PROP_GRID, true));
    reverseContigs.setSelected(prefs.getBoolean(DotPlotViewerPanel.PROP_REVERSE, true));
    stackContigs.setSelected(prefs.getBoolean(DotPlotViewerPanel.PROP_STACK, true));
  }

  void store() {
    prefs.putBoolean(DotPlotViewerPanel.PROP_GRID, grid.isSelected());
    prefs.putBoolean(DotPlotViewerPanel.PROP_REVERSE, reverseContigs.isSelected());
    prefs.putBoolean(DotPlotViewerPanel.PROP_STACK, stackContigs.isSelected());
  }

  boolean valid() {
    // TODO check whether form is consistent and complete
    return true;
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox grid;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JCheckBox reverseContigs;
  private javax.swing.JCheckBox stackContigs;
  // End of variables declaration//GEN-END:variables
}
